'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createRequire}=require('node:module');
const {database}=require('./helpers/postgres-test-db');
test('real importer dry run, rerun, shared links and unverified rows preserve existing records',async()=>{
  const db=database();
  try {
    db.exec(`CREATE TABLE pro_profiles(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,business_name TEXT,category TEXT,bio TEXT,city TEXT,state TEXT,workplace_name TEXT,street_address TEXT,zip_code TEXT,booking_url TEXT,initials TEXT,claim_status TEXT,source_url TEXT,source_name TEXT,source_checked_at TIMESTAMPTZ);
      CREATE TABLE pro_categories(pro_id BIGINT,category TEXT,PRIMARY KEY(pro_id,category), CONSTRAINT pro_categories_category_check CHECK (category IN ('barber','stylist')));`);
    db.exec(fs.readFileSync(path.join(__dirname,'../db/migrations/20261002_makeup_wedding_categories.sql'),'utf8'));
    const row={name:'Internal fixture',category:'makeup_artist',workplace_name:'Fixture workplace',city:'Denver',state:'CO',address:'123 Test St',zip:'80202',booking_url:'https://fixture.glossgenius.com/services',source_url:'https://fixture.glossgenius.com/about',source_name:'GlossGenius',_verification_tier:'page_opened'};
    const filename=path.join(__dirname,'../scripts/import-unclaimed-profiles.js'),localRequire=createRequire(filename);
    function run(rows,dryRun=false){
      let report;
      const fsShim={...fs,readFileSync:()=>JSON.stringify(rows),mkdirSync(){},writeFileSync:(_p,v)=>{report=JSON.parse(v);}};
      const dbShim={...db,prepare(sql){return /pg_advisory_xact_lock/.test(sql)?{get(){}}:db.prepare(sql);}};
      vm.runInNewContext(fs.readFileSync(filename,'utf8'),{require:name=>name==='../db'?dbShim:name==='node:fs'?fsShim:localRequire(name),process:{argv:['node','import','fixture.json','--report=report.json',...(dryRun?['--dry-run']:[])]},console:{log(){},warn(){}},URL,Date});
      return report;
    }
    assert.equal(run([row],true).summary.inserted,1);
    assert.equal(db.prepare('SELECT count(*) AS n FROM pro_profiles').get().n,0);
    assert.equal(run([row]).summary.inserted,1);
    assert.equal(run([{...row,address:'Changed address',booking_url:row.booking_url+'?utm_source=test'}]).summary.duplicates,1);
    assert.equal(run([{...row,name:'Different professional'}]).duplicates[0].reason,'shared_booking_url_requires_review');
    assert.equal(run([{...row,name:'Unverified',booking_url:'https://other.glossgenius.com/services',_verification_tier:'snippet'}]).rejected[0].reason,'verification_required');
    assert.equal(run([{...row,name:'Unsafe',booking_url:'https://user:password@other.glossgenius.com/services'}]).rejected[0].reason,'invalid_booking_url');
    const persisted=db.prepare('SELECT * FROM pro_profiles').get();
    assert.equal(persisted.user_id,null);assert.equal(persisted.claim_status,'unclaimed');assert.equal(persisted.street_address,row.address);assert.equal(persisted.source_url,row.source_url);
    assert.equal(db.prepare('SELECT count(*) AS n FROM pro_profiles').get().n,1);
    assert.equal(db.prepare('SELECT count(*) AS n FROM pro_categories').get().n,1);
    assert.throws(()=>db.prepare('INSERT INTO pro_categories(pro_id,category) VALUES (?,?)').run(persisted.id,'plumber'),/check constraint/);
  }finally{await db.close();}
});
