'use strict';
const db=require('../db'); const {layout}=require('../lib/layout'); const {send,redirect,flashFromQuery}=require('../lib/http'); const {escapeHtml}=require('../lib/util');
const {createCheckoutSession,createPortalSession,stripeShopPriceId}=require('../lib/stripe');
function shop(ctx){ if(!ctx.currentUser){redirect(ctx.res,'/login?next='+encodeURIComponent('/dashboard/shop/billing'));return null;} const s=db.prepare("SELECT * FROM shops WHERE owner_user_id=? AND claim_status='claimed' ORDER BY id DESC LIMIT 1").get(ctx.currentUser.id); if(!s){redirect(ctx.res,'/dashboard/shop');return null;} return s; }
module.exports=function(router){
 router.get('/dashboard/shop/billing',async ctx=>{const s=shop(ctx);if(!s)return;const sub=db.prepare('SELECT * FROM shop_subscriptions WHERE shop_id=?').get(s.id);const configured=Boolean(process.env.STRIPE_SECRET_KEY&&stripeShopPriceId()&&process.env.APP_URL);const connected=Boolean(sub&&sub.provider_customer_id);
 const button=!configured?'<button class="btn secondary" disabled>Set up payment</button><p class="helptext">Shop billing activates after STRIPE_SHOP_PRICE_ID is configured.</p>':connected?`<form method="POST" action="/dashboard/shop/billing/portal"><input type="hidden" name="_csrf" value="${escapeHtml(ctx.session.csrf_token)}"><button class="btn secondary">Manage payment & subscription</button></form>`:`<form method="POST" action="/dashboard/shop/billing/checkout"><input type="hidden" name="_csrf" value="${escapeHtml(ctx.session.csrf_token)}"><button class="btn">Set up secure payment</button></form>`;
 const body=`<section class="section container" style="max-width:900px;"><div class="section-head"><div><h1>Shop billing</h1><p class="muted">${escapeHtml(s.name)}</p></div><a class="btn secondary" href="/dashboard/shop">Shop dashboard</a></div><div class="panel"><p class="muted">GoBookr Shop</p><h2>$35 <span class="muted" style="font-size:16px;font-weight:500">/ month</span></h2><p>Your shop page is billed separately from individual professional profiles.</p><span class="badge category">${escapeHtml((sub&&sub.status)||'inactive')}</span></div><div class="panel"><h3>Payment & subscription</h3><p class="muted">Payments are securely processed by Stripe.</p>${button}</div></section>`;
 send(ctx.res,layout({title:'Shop billing',currentUser:ctx.currentUser,session:ctx.session,flash:flashFromQuery(ctx.query),body}));});
 router.post('/dashboard/shop/billing/checkout',async ctx=>{const s=shop(ctx);if(!s)return;if(!process.env.STRIPE_SECRET_KEY||!stripeShopPriceId()||!process.env.APP_URL)return redirect(ctx.res,'/dashboard/shop/billing?error='+encodeURIComponent('Shop billing is not configured yet.'));let sub=db.prepare('SELECT * FROM shop_subscriptions WHERE shop_id=?').get(s.id);if(!sub){db.prepare("INSERT INTO shop_subscriptions (shop_id,status,plan_code) VALUES (?,'inactive','shop_monthly_35')").run(s.id);sub=db.prepare('SELECT * FROM shop_subscriptions WHERE shop_id=?').get(s.id);}if(sub.provider_customer_id)return redirect(ctx.res,'/dashboard/shop/billing');try{const x=await createCheckoutSession({shopId:s.id,email:ctx.currentUser.email});redirect(ctx.res,x.url);}catch(e){console.error(e);redirect(ctx.res,'/dashboard/shop/billing?error='+encodeURIComponent('Could not start secure checkout.'));}});
 router.post('/dashboard/shop/billing/portal',async ctx=>{const s=shop(ctx);if(!s)return;const sub=db.prepare('SELECT * FROM shop_subscriptions WHERE shop_id=?').get(s.id);if(!sub||!sub.provider_customer_id)return redirect(ctx.res,'/dashboard/shop/billing');try{const p=await createPortalSession(sub.provider_customer_id);redirect(ctx.res,p.url);}catch(e){console.error(e);redirect(ctx.res,'/dashboard/shop/billing?error='+encodeURIComponent('Could not open subscription management.'));}});
};
