'use strict';
const {escapeHtml:e}=require('./util');
const {renderSupportEmail}=require('./support-email-view');
const {STATUS_LABELS,FILTER_LABELS}=require('./support-status');
const {shell,employeeShell}=require('./staff-views');
const wrap=(title,body,owner)=>owner?shell(title,body,'/owner','support'):employeeShell(title,body,'support',true);
function notice(saved){const messages={read:'Ticket marked as read.',ticket:'Assignment and status saved.',draft:'Draft saved. No email was sent.'};return Object.hasOwn(messages,saved)?`<div class="staff-notice" role="status">${messages[saved]}</div>`:'';}
function inbox(tickets,owner,filter='all'){const base=owner?'/owner/support':'/staff/support';return wrap('Support inbox',`<div class="staff-section-heading"><h2>Customer support</h2><p>Microsoft 365 is not connected yet. Incoming email and sending are unavailable.</p></div><nav class="support-filters" aria-label="Ticket filters">${Object.keys(FILTER_LABELS).map(f=>`<a href="${base}?filter=${f}"${filter===f?' aria-current="page"':''}>${FILTER_LABELS[f]}</a>`).join('')}</nav><section class="staff-section"><h2>${owner?'Team inbox':'Assigned to you'}</h2>${tickets.length?`<p>${tickets.filter(t=>t.unread).length} unread in the latest ${tickets.length} tickets.</p>${tickets.map(t=>`<a class="staff-roster-row support-ticket-row" href="${base}/${t.id}"><span><strong>${e(t.subject||'No subject')}</strong><span>${t.unread?'Unread · ':''}${e(STATUS_LABELS[t.status]||'Unknown status')}${t.assignee_name?' · '+e(t.assignee_name):''}</span></span><span aria-hidden="true">→</span></a>`).join('')}`:`<div class="staff-empty"><h3>${filter==='all'?'No support tickets yet':'No tickets match this filter'}</h3><p>${filter==='all'?'Real messages will appear after the mailbox is connected.':'Choose All to see the latest tickets you can access.'}</p></div>`}</section>`,owner);}
function detail(t,members,owner,canReply,csrf,saved){const base=owner?'/owner/support':'/staff/support';const hidden=`<input type="hidden" name="_csrf" value="${e(csrf)}">`;return wrap('Support ticket',`${notice(saved)}<a class="staff-edit" href="${base}">Back to inbox</a><section class="staff-section"><h2>${e(t.subject||'No subject')}</h2><p>${e(STATUS_LABELS[t.status]||'Unknown status')}</p><form method="POST" action="${base}/${t.id}/read">${hidden}<button class="btn secondary" type="submit">Mark as read</button></form></section>${owner?`<section class="staff-section"><h2>Assignment and status</h2><form class="staff-form" method="POST" action="${base}/${t.id}/manage">${hidden}<input type="hidden" name="version" value="${t.version}"><label class="staff-field">Assign to<select name="assignee_id"><option value="">Unassigned</option>${members.filter(m=>m.status==='active'&&m.permissions.includes('support.read')).map(m=>`<option value="${m.id}"${Number(t.assignee_id)===Number(m.id)?' selected':''}>${e(m.name)}</option>`).join('')}</select></label><label class="staff-field">Status<select name="status">${Object.entries(STATUS_LABELS).map(([key,label])=>`<option value="${key}"${t.status===key?' selected':''}>${label}</option>`).join('')}</select></label><button class="staff-add-button" type="submit">Save</button></form></section>`:''}<section class="staff-section"><h2>Messages</h2><p class="staff-help">Showing up to 50 latest messages.</p>${t.messages.map(m=>renderSupportEmail({subject:t.subject,sender:m.sender,bodyText:m.body_text})).join('')||'<p>No messages available.</p>'}</section>${canReply?`<section class="staff-section"><h2>Reply draft</h2><p class="staff-help">Save a draft for yourself. Sending is disabled until Microsoft 365 is connected. No email will be sent.</p><form class="staff-form" method="POST" action="${base}/${t.id}/draft">${hidden}<input type="hidden" name="version" value="${t.draft?.version||0}"><label class="staff-field">Draft<textarea name="body_text" rows="6" maxlength="10000" required>${e(t.draft?.body_text||'')}</textarea></label><button class="staff-add-button" type="submit">Save draft</button></form></section>`:''}<section class="staff-section"><h2>Activity</h2>${t.events.map(v=>`<div class="staff-row"><div><strong>${e({read:'Marked as read',assigned:'Assignment updated',status_updated:'Status updated',draft_saved:'Draft saved'}[v.action]||v.action)}</strong><p>${e(String(v.created_at))}</p></div></div>`).join('')||'<p>No activity yet.</p>'}</section>`,owner);}
module.exports={inbox,detail};
