'use strict';
const validId=n=>Number.isSafeInteger(n)&&n>0;
function createSupportStore(pool){
 async function tx(fn){const c=await pool.connect();try{await c.query('BEGIN');const result=await fn(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async function access(c,a,isOwner,permission='support.read'){
  if(!validId(a?.userId)||typeof a?.token!=='string'||!a.token)throw Error('Support access required');
  if(isOwner){const row=(await c.query(`SELECT o.user_id FROM staff_ops.owners o JOIN public.sessions s ON s.user_id=o.user_id WHERE o.user_id=$1 AND s.token=$2 AND s.expires_at>CURRENT_TIMESTAMP FOR SHARE OF o,s`,[a.userId,a.token])).rows[0];if(!row)throw Error('Owner access required');return{ownerId:a.userId};}
  const m=(await c.query(`SELECT m.* FROM staff_ops.members m JOIN public.sessions s ON s.user_id=m.user_id WHERE m.user_id=$1 AND m.status='active' AND s.token=$2 AND s.expires_at>CURRENT_TIMESTAMP FOR SHARE OF m,s`,[a.userId,a.token])).rows[0];
  if(!m||!m.permissions.includes(permission)||!m.permissions.includes('support.read'))throw Error('Support access required');
  return{ownerId:Number(m.owner_id),memberId:Number(m.id)};
 }
 async function ticket(c,a,id,isOwner,permission){if(!validId(id))throw Error('Ticket not found');const scope=await access(c,a,isOwner,permission);const row=(await c.query(`SELECT t.* FROM staff_ops.support_tickets t WHERE t.id=$1 AND t.owner_id=$2 ${isOwner?'':'AND t.assignee_id=$3'} FOR UPDATE`,isOwner?[id,scope.ownerId]:[id,scope.ownerId,scope.memberId])).rows[0];if(!row)throw Error('Ticket not found');return row;}
 async function event(c,a,t,action){await c.query('INSERT INTO staff_ops.support_events(ticket_id,actor_id,action,ticket_version,details) VALUES($1,$2,$3,$4,$5::jsonb)',[t.id,a.userId,action,t.version,JSON.stringify({status:t.status,assignee_id:t.assignee_id})]);}
 async function list(a,isOwner=false,filter='all'){if(!['all','open','assigned','resolved'].includes(filter))throw Error('Invalid inbox filter');const filterSql=filter==='open'?"AND t.status='open'":filter==='resolved'?"AND t.status='resolved'":filter==='assigned'?'AND t.assignee_id IS NOT NULL':'';return tx(async c=>{const s=await access(c,a,isOwner);return(await c.query(`SELECT t.id,t.subject,t.status,t.version,t.updated_at,m.name AS assignee_name,COALESCE(msg.latest,0)>COALESCE(r.last_message_id,0) AS unread FROM staff_ops.support_tickets t LEFT JOIN staff_ops.members m ON m.id=t.assignee_id LEFT JOIN LATERAL (SELECT MAX(id) AS latest FROM staff_ops.support_messages WHERE ticket_id=t.id) msg ON true LEFT JOIN staff_ops.support_reads r ON r.ticket_id=t.id AND r.user_id=$1 WHERE t.owner_id=$2 ${isOwner?'':'AND t.assignee_id=$3'} ${filterSql} ORDER BY t.updated_at DESC,t.id DESC LIMIT 100`,isOwner?[a.userId,s.ownerId]:[a.userId,s.ownerId,s.memberId])).rows;});}
 async function get(a,id,isOwner=false){return tx(async c=>{const t=await ticket(c,a,id,isOwner);t.messages=(await c.query('SELECT id,sender,body_text,received_at FROM staff_ops.support_messages WHERE ticket_id=$1 ORDER BY id DESC LIMIT 50',[id])).rows.reverse();t.draft=(await c.query('SELECT body_text,version FROM staff_ops.support_drafts WHERE ticket_id=$1 AND user_id=$2',[id,a.userId])).rows[0];t.events=(await c.query('SELECT action,created_at FROM staff_ops.support_events WHERE ticket_id=$1 ORDER BY id DESC LIMIT 50',[id])).rows;return t;});}
 async function markRead(a,id,isOwner=false){return tx(async c=>{const t=await ticket(c,a,id,isOwner);await c.query(`INSERT INTO staff_ops.support_reads(ticket_id,user_id,last_message_id) SELECT $1,$2,COALESCE(MAX(id),0) FROM staff_ops.support_messages WHERE ticket_id=$1 ON CONFLICT(ticket_id,user_id) DO UPDATE SET last_message_id=EXCLUDED.last_message_id,read_at=CURRENT_TIMESTAMP`,[id,a.userId]);await event(c,a,t,'read');});}
 async function update(a,id,version,input){if(!validId(version))throw Error('Invalid ticket version');return tx(async c=>{const t=await ticket(c,a,id,true);if(t.version!==version)throw Error('Ticket changed; reload before editing');const assignee=input.assignee_id===''?null:Number(input.assignee_id);if(assignee!==null&&!validId(assignee))throw Error('Invalid assignee');if(assignee!==null){const m=(await c.query(`SELECT id FROM staff_ops.members WHERE id=$1 AND owner_id=$2 AND status='active' AND 'support.read'=ANY(permissions) FOR SHARE`,[assignee,a.userId])).rows[0];if(!m)throw Error('Employee needs active support read access');}if(!['open','resolved'].includes(input.status))throw Error('Invalid status');const row=(await c.query('UPDATE staff_ops.support_tickets SET assignee_id=$2,status=$3,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *',[id,assignee,input.status])).rows[0];if(String(t.assignee_id)!==String(assignee))await event(c,a,row,'assigned');await event(c,a,row,'status_updated');return row;});}
 async function saveDraft(a,id,version,body,isOwner=false){if(!Number.isSafeInteger(version)||version<0||typeof body!=='string'||!body.trim()||body.length>10000)throw Error('Invalid reply draft');return tx(async c=>{const t=await ticket(c,a,id,isOwner,'support.reply');const d=(await c.query('SELECT version FROM staff_ops.support_drafts WHERE ticket_id=$1 AND user_id=$2 FOR UPDATE',[id,a.userId])).rows[0];if((d?.version||0)!==version)throw Error('Draft changed; reload before editing');await c.query(`INSERT INTO staff_ops.support_drafts(ticket_id,user_id,body_text) VALUES($1,$2,$3) ON CONFLICT(ticket_id,user_id) DO UPDATE SET body_text=EXCLUDED.body_text,version=staff_ops.support_drafts.version+1,updated_at=CURRENT_TIMESTAMP`,[id,a.userId,body.trim()]);await event(c,a,t,'draft_saved');});}
 return{list,get,markRead,update,saveDraft};
}
module.exports={createSupportStore};
